# Generated by Django 3.0.2 on 2020-01-27 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalator',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('score', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('Instalator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_oper_face.Instalator')),
            ],
        ),
    ]
