# Generated by Django 3.0.2 on 2020-02-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalator',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='айди инсталлятора')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Общий счёт')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('date', models.CharField(max_length=200, verbose_name='Время')),
                ('start_answer', models.TextField(verbose_name='Стартовый отчет')),
                ('finish_answer', models.TextField(verbose_name='Финальный отчет')),
                ('photo_1', models.ImageField(upload_to='main_oper_face/static', verbose_name='Выполнена ли проводка кабеля в подъезде?')),
                ('photo_2', models.ImageField(upload_to='main_oper_face/static', verbose_name='Необходимо ли проделать доп. отверстие для ввода кабеля в жилое помещение?')),
                ('photo_3', models.ImageField(upload_to='main_oper_face/static', verbose_name='Необходимо ли проделать доп отверстие в помещении?')),
                ('photo_4', models.ImageField(upload_to='main_oper_face/static', verbose_name='Логин и пароль от Wi-Fi сети наклеен на оборудование?')),
                ('photo_5', models.ImageField(upload_to='main_oper_face/static', verbose_name='Продемонстрирована скорость подключения?')),
                ('Instalator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_oper_face.Instalator')),
            ],
        ),
    ]
