# Generated by Django 3.0.2 on 2020-01-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='photo',
            field=models.FilePathField(path='/home/tester-vmn/projects/inventBotPilot/instal_photo/', recursive=True, verbose_name='путь к фото'),
        ),
    ]
