# Generated by Django 3.0.2 on 2020-01-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalator',
            name='chat_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='айди инсталлятора'),
        ),
        migrations.AlterField(
            model_name='instalator',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='instalator',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='Общий счёт'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='answer',
            field=models.TextField(verbose_name='Ответы на вопросы'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='date',
            field=models.CharField(max_length=200, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Местоположение'),
        ),
    ]
