# Generated by Django 3.0.2 on 2020-01-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Installations',
            new_name='Installation',
        ),
    ]
