# Generated by Django 3.0.2 on 2020-01-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0002_auto_20200130_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='photo',
        ),
        migrations.AddField(
            model_name='installation',
            name='photo_1',
            field=models.FilePathField(default='NULL', path='/home/tester-vmn/projects/inventBotPilot/instal_photo/', recursive=True, verbose_name='Фото ОКР'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='photo_2',
            field=models.FilePathField(default='NULL', path='/home/tester-vmn/projects/inventBotPilot/instal_photo/', recursive=True, verbose_name='Фото кабеля в подъезде'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='photo_3',
            field=models.FilePathField(default='NULL', path='/home/tester-vmn/projects/inventBotPilot/instal_photo/', recursive=True, verbose_name='Фото вводного отверстия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='photo_4',
            field=models.FilePathField(default='NULL', path='/home/tester-vmn/projects/inventBotPilot/instal_photo/', recursive=True, verbose_name='Фото кабеля в помещении'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='photo_5',
            field=models.FilePathField(default='NULL', path='/home/tester-vmn/projects/inventBotPilot/instal_photo/', recursive=True, verbose_name='Фото дополнительного отверстия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='photo_6',
            field=models.FilePathField(default='NULL', path='/home/tester-vmn/projects/inventBotPilot/instal_photo/', recursive=True, verbose_name='Фото абонентоского оборудования'),
            preserve_default=False,
        ),
    ]
