# Generated by Django 3.0.2 on 2020-01-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0002_auto_20200126_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='time',
        ),
    ]
