# Generated by Django 3.0.2 on 2020-01-26 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0003_auto_20200126_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
