# Generated by Django 3.0.2 on 2020-01-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0003_auto_20200130_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='photo_1',
            field=models.FilePathField(path='/home/tester-vmn/projects/inventBotPilot/operface/main_oper_face/static/', recursive=True, verbose_name='Фото ОКР'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo_2',
            field=models.FilePathField(path='/home/tester-vmn/projects/inventBotPilot/operface/main_oper_face/static/', recursive=True, verbose_name='Фото кабеля в подъезде'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo_3',
            field=models.FilePathField(path='/home/tester-vmn/projects/inventBotPilot/operface/main_oper_face/static/', recursive=True, verbose_name='Фото вводного отверстия'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo_4',
            field=models.FilePathField(path='/home/tester-vmn/projects/inventBotPilot/operface/main_oper_face/static/', recursive=True, verbose_name='Фото кабеля в помещении'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo_5',
            field=models.FilePathField(path='/home/tester-vmn/projects/inventBotPilot/operface/main_oper_face/static/', recursive=True, verbose_name='Фото дополнительного отверстия'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo_6',
            field=models.FilePathField(path='/home/tester-vmn/projects/inventBotPilot/operface/main_oper_face/static/', recursive=True, verbose_name='Фото абонентоского оборудования'),
        ),
    ]
