# Generated by Django 3.0.2 on 2020-01-26 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0004_installation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='photo',
            field=models.FilePathField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
