# Generated by Django 3.0.2 on 2020-01-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0004_auto_20200131_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='photo_1',
            field=models.ImageField(upload_to='static/', verbose_name='Фото ОКР'),
        ),
    ]
