# Generated by Django 3.0.2 on 2020-01-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0005_installation_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='photo',
        ),
    ]
