# Generated by Django 3.0.2 on 2020-01-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_oper_face', '0006_auto_20200131_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='photo_6',
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo_1',
            field=models.ImageField(upload_to='main_oper_face/static', verbose_name='Выполнена ли проводка кабеля в подъезде?'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo_2',
            field=models.ImageField(upload_to='main_oper_face/static', verbose_name='Необходимо ли проделать доп. отверстие для ввода кабеля в жилое помещение?'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo_3',
            field=models.ImageField(upload_to='main_oper_face/static', verbose_name='Необходимо ли проделать доп отверстие в помещении?'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo_4',
            field=models.ImageField(upload_to='main_oper_face/static', verbose_name='Логин и пароль от Wi-Fi сети наклеен на оборудование?'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo_5',
            field=models.ImageField(upload_to='main_oper_face/static', verbose_name='Продемонстрирована скорость подключения?'),
        ),
    ]
